### ISSUE TITLE
RPGChat

### ISSUE THREAD

**Issue by Aixory** [SirZontax/RPGChat#8]
Hello SirZiegenKease,

I would love to use RPGChat to my server now I wonder is it possible to fix the chat when the character moves the text is like follow the character in delay it's not sticking with the player..
plus is it possible to provide support for place holder? so I can add emojis by default for every message?
Here's an example of what I mean:
https://cdn.discordapp.com/attachments/889887581473497140/889893404941623296/Screenshot_20210920-095730_Discord.png

Thank you for reading this request
Best regards,
Aixory

**Comment by SirZontax** [comment]
Hey, First of all thanks!

I discovered the problem with the "delay" already at the beginning. It's caused mostly because it updates the position of it every tick which might look not smooth enough. I'm still looking for a better solution but it was only minor priority, which I'll set to high priority on my list (scheduled for Update 1.7.1). 

I never worked with Placeholder but I'll consider it for the next feature update (scheduled for 1.8.0). I don't know if it's possible to use with Whispered Chat but normal should work fine. 

If anything changes it will be written here.

Thanks for your suggestions and feedback.
Best regards,
SirZiegenKease

**Comment by SirZontax** [comment]
Done.
